import Head from 'next/head'
import CustomButton from '../Components/CustomButton'
import useGlobalState from '../Hooks/useGlobalState'
import Main from '../page/Main'
import { useAddress } from '@thirdweb-dev/react'

export default function Home() {

  const { connect } = useGlobalState()
  const address = useAddress()
  console.log(address)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='linear-gradient'>

        {address===undefined ? (
          <div className="flex justify-center items-center h-screen">
            <CustomButton
              btnType="button"
              title={'Connect'}
              styles={'bg-[#8c6dfd] h-20 w-52 text-2xl'}
              handleClick={connect}
            />
          </div>
        ) : <Main />}
      </div>
    </>
  )
}
